FROM node:22-alpine

WORKDIR /usr/src/app 

COPY package*.json ./

#npm ci ( clean install) over npm install as ci strictly downloads packages without updating them.( this avoids bugs)
RUN npm ci

#copy rest of the code into our container
COPY . .

ENV PORT=3000

EXPOSE 3000

CMD ["npm", "start"]
